trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - main
    - develop
  paths:
    exclude:
    - docker
    - docs
    - docs.md
    - examples
    - README.md
    - CHANGELOG.md

variables:
  tagged: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]
  releaseDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  version: ''

stages:
  - stage: DarcyAI
    jobs:
      - job: DarcyAI
        workspace:
          clean: all
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          matrix:
            Build:
              python.version: '3.7'

        steps:
        - checkout: self
          persistCredentials: true
          clean: true
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(python.version)'
          displayName: 'Use Python $(python.version)'

        - script: |
            set -e
            sudo echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
            sudo echo "deb https://packages.cloud.google.com/apt coral-cloud-stable main" | sudo tee /etc/apt/sources.list.d/coral-cloud.list
            sudo curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update
            sudo apt-get install -y python3-pycoral
            sudo apt-get clean
            sudo rm -rf /var/lib/apt/lists/*
            python -m pip install --extra-index-url https://google-coral.github.io/py-repo/ pycoral~=2.0
            python -m pip install --upgrade pip build
            python -m pip install -r ./requirements.txt
            python -m pip install pytest-azurepipelines pytest-cov
          displayName: 'Install dependencies'

        - script: |
            set -e
            pylint --rcfile=.pylintrc --output-format=colorized --reports=n --score=n src/darcyai/
          displayName: 'Run pylint'

        - script: |
            set -e
            pytest src/darcyai/tests -v --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml
          displayName: 'Run unit tests'

        - task: PublishTestResults@2
          condition: succeededOrFailed()
          inputs:
            testResultsFiles: '**/test-*.xml'
            testRunTitle: 'Publish test results'
          displayName: 'Publish test results'

        - task: PublishCodeCoverageResults@1
          inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
          displayName: 'Publish code coverage'

        - script: |
            set -e

            NEXT_VERSION=$(cat next_version)
            MAJOR=$(echo "$NEXT_VERSION" | tr -d "v" | sed "s|-.*||" | sed -E "s|(.)\..\..|\1|g")
            MINOR=$(echo "$NEXT_VERSION" | tr -d "v" | sed "s|-.*||" | sed -E "s|.\.(.)\..|\1|g")
            PATCH=$(echo "$NEXT_VERSION" | tr -d "v" | sed "s|-.*||" | sed -E "s|.\..\.(.)|\1|g")
            SUFFIX="dev$(Build.BuildNumber)"
            VERSION="$NEXT_VERSION-$SUFFIX"
            echo "VERSION: $VERSION"

            git config --global user.email "info@edgeworx.io"
            git config --global user.name "Edgeworx"
            bump2version build --new-version $VERSION
            git config --global user.email ""
            git config --global user.name ""
          displayName: 'Change version'

        - script: |
            set -e
            python3 -m build
          displayName: 'Artifact creation'

        - task: CopyFiles@2
          inputs:
            targetFolder: $(Build.ArtifactStagingDirectory)
          displayName: 'Copy files'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
            ArtifactName: 'dist'
            publishLocation: 'Container'
          displayName: 'Publish build artifacts'

  - stage: E2E_Tests
    dependsOn: DarcyAI
    jobs:
      - template: e2e-test-template.yaml
        parameters:
          name: 'E2E_x86'
          poolImageName: 'Azure Pipelines'
          imageTag: 'dev'

      - template: e2e-test-template.yaml
        parameters:
          name: 'E2E_arm32'
          poolImageName: 'build-farm-rpi4'
          imageTag: 'dev'

      - template: e2e-test-template.yaml
        parameters:
          name: 'E2E_arm64'
          poolImageName: 'build-farm-coral'
          imageTag: 'dev'

      - template: e2e-test-template.yaml
        parameters:
          name: 'E2E_macOS'
          poolImageName:
            vmImage: 'macOS-latest'
          imageTag: 'dev'

      # - template: e2e-test-template.yaml
      #   parameters:
      #     name: 'E2E_windows'
      #     poolImageName:
      #       vmImage: 'windows-2019'
      #     imageTag: 'dev'

  - stage: Release
    dependsOn: E2E_Tests
    condition: or(eq(variables['tagged'], true), eq(variables['releaseDev'], true))
    jobs:
      - job: Release
        workspace:
          clean: all
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          matrix:
            Build:
              python.version: '3.7'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: dist
              patterns: '**/*.whl'
              path: $(System.DefaultWorkingDirectory)/dist
            displayName: 'Download artifacts'

          - script: |
              set -e
              python3 -m pip install --upgrade pip --user
              python3 -m pip install --upgrade twine --user
            displayName: 'Install dependencies'

          - task: TwineAuthenticate@1
            inputs:
              pythonUploadServiceConnection: 'PyPI'
            displayName: 'Authenticate to PyPI'

          - script: |
              set -e
              python3 -m twine upload -r pypi --config-file $(PYPIRC_PATH) ./dist/*.whl --verbose
            displayName: 'Publish to PyPI'
