jobs:
  - job: ${{ parameters.name }}
    dependsOn: DarcyAI
    workspace:
      clean: all
    pool: ${{ parameters.poolImageName }}
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: dist
          patterns: '**/*.whl'
          path: $(System.DefaultWorkingDirectory)/dist
          displayName: 'Download artifacts'
      - script: |
          python3 -m pip install --upgrade pip --user
        displayName: 'install dependencies'
      - bash: |
          cd $(System.DefaultWorkingDirectory)/src/darcyai/integration_tests
          python3 -m pip install -r requirements.txt --user
          python3 -m pip install $(System.DefaultWorkingDirectory)/dist/darcyai*.whl --user

          python3 -u tests.py
        displayName: 'e2e test on macOS and Linux'
        condition: ne( variables['Agent.OS'], 'Windows_NT' )
      - powershell: |
          cd $(System.DefaultWorkingDirectory)\src\darcyai\integration_tests
          python3 -m pip install -r requirements.txt --user
          dir $(System.DefaultWorkingDirectory)\
          dir $(System.DefaultWorkingDirectory)\dist\
          python3 -m pip install $(System.DefaultWorkingDirectory)\dist\darcyai*.whl --user

          python3 -u tests.py
        displayName: 'e2e test on Windows'
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
      - bash: |
          sudo find $(Build.Repository.LocalPath) -name "__pycache__" -type d -exec /bin/rm -rf {} +
        displayName: 'cleanup on macOS and Linux'
        condition: and(ne( variables['Agent.OS'], 'Windows_NT' ), always())
