trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - main
  paths:
    include:
      - docker
    exclude:
      - docker/README.md
      - docker/CHANGELOG.md
pr: none
  
pool: 'Azure Pipelines'

variables:
  DOCKER_CLI_EXPERIMENTAL: enabled
  imageName: 'darcyai/darcyai'
  imageTag: 'dev'

steps:
- script: |
    RELEASE_TAG=$(git describe --tags --abbrev=0)
    echo "##vso[task.setvariable variable=imageTag]$RELEASE_TAG"
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  displayName: 'Set image tag'

- script: |
    sudo apt-get install -y qemu-user-static
    sudo apt-get install -y binfmt-support
    docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  displayName: 'Install prerequisites'

- task: Docker@2
  displayName: Login to Dockerhub
  inputs:
    command: login
    containerRegistry: DarcyAI-Dockerhub

- template: ./docker-task-template.yml
  parameters:
    imageName: '$(imageName)-base'
    imageTag: $(imageTag)
    dockerFile: 'docker/base/Dockerfile'
    step: base

- template: ./docker-task-template.yml
  parameters:
    imageName: '$(imageName)-coral'
    imageTag: $(imageTag)
    dockerFile: 'docker/coral/Dockerfile'
    step: coral

- template: ./docker-task-template.yml
  parameters:
    imageName: '$(imageName)-cpu'
    imageTag: $(imageTag)
    dockerFile: 'docker/cpu/Dockerfile'
    step: cpu

- template: ./docker-task-template.yml
  parameters:
    imageName: '$(imageName)'
    imageTag: $(imageTag)
    dockerFile: 'docker/universal/Dockerfile'
    step: universal
